# language: php
# tests: true

coding_style:
  php:
    indentation:
      general:
        use_tabs: false
        size: 4

build:
  nodes:
    tests: true
    analysis:
      tests:
        override:
          -
            command: phpcs-run
            use_website_config: true
          - php-scrutinizer-run

checks:
  php:
    duplication: false
